gems:
    - jekyll-seo-tag
    - jekyll-sitemap
    
title: Hersh Amin
description: Aerospace Engineer, Software Engineer, Aviator, Entrepreneur
url: http://hershamin.me
author: Hersh Amin
logo: /img/avatar.png

image:
    facebook: /img/avatar.png
    twitter: /img/avatar.png
    height: 200
    width: 200

twitter:
    username: hersh_amin

social:
    name: Hersh Amin
    links:
        - https://twitter.com/hersh_amin
        - https://www.linkedin.com/in/hershamin
        - https://github.com/hershamin